SELECT
ss_id,
subsnp_orientation,
rs_id,
snp_orientation,
contig_name,
contig_start,
contig_end,
contig_orientation,
loc_type,
chromosome,
chromosome_start,
chromosome_end,
reference_c,
reference_t,
alternate,
alleles,
hgvs_c_string,
hgvs_c_start,
hgvs_c_stop,
hgvs_c_orientation,
hgvs_t_string,
hgvs_t_start,
hgvs_t_stop,
hgvs_t_orientation,
batch_id
from
dbsnp_chicken_9031.dbsnp_variant_load_d8c757988871529f37061fa9c79477a5
WHERE rs_id =
